import { Role } from './types';

// URLs de imagens de zathong.com, conforme solicitado, para corrigir problemas de visualização.
export const ITEM_ICONS: Record<string, string> = {
    "Couraça Antiga": "https://zathong.com/wp-content/uploads/2022/10/Antique-Cuirass.webp",
    "Botas Arcanas": "https://zathong.com/wp-content/uploads/2022/10/Arcane-Boots.webp",
    "Cinto de Ares": "https://zathong.com/wp-content/uploads/2022/10/Ares-Belt.webp",
    "Escudo de Atena": "https://zathong.com/wp-content/uploads/2022/10/Athenas-Shield.webp",
    "Lâmina do Azure": "https://zathong.com/wp-content/uploads/2022/10/Azure-Blade.webp",
    "Fúria do Berserker": "https://zathong.com/wp-content/uploads/2022/10/Berserkers-Fury.webp",
    "Escudo de Gelo Negro": "https://zathong.com/wp-content/uploads/2022/10/Black-Ice-Shield.webp",
    "Armadura de Lâminas": "https://zathong.com/wp-content/uploads/2022/10/Blade-Armor.webp",
    "Lâmina do Desespero": "https://zathong.com/wp-content/uploads/2022/10/Blade-of-Despair.webp",
    "Lâmina dos Sete Mares": "https://zathong.com/wp-content/uploads/2022/10/Blade-of-the-Heptaseas.webp",
    "Asas Sanguinárias": "https://zathong.com/wp-content/uploads/2022/10/Blood-Wings.webp",
    "Peitoral da Força Bruta": "https://zathong.com/wp-content/uploads/2022/10/Brute-Force-Breastplate.webp",
    "Relógio do Destino": "https://zathong.com/wp-content/uploads/2022/10/Clock-of-Destiny.webp",
    "Energia Concentrada": "https://zathong.com/wp-content/uploads/2022/10/Concentrated-Energy.webp",
    "Foice da Corrosão": "https://zathong.com/wp-content/uploads/2022/10/Corrosion-Scythe.webp",
    "Elmo Amaldiçoado": "https://zathong.com/wp-content/uploads/2022/10/Cursed-Helmet.webp",
    "Espada do Caçador de Demônios": "https://zathong.com/wp-content/uploads/2022/10/Demon-Hunter-Sword.webp",
    "Sapatos de Demônio": "https://zathong.com/wp-content/uploads/2022/10/Demon-Shoes.webp",
    "Glaive Divino": "https://zathong.com/wp-content/uploads/2022/10/Divine-Glaive.webp",
    "Dominância de Gelo": "https://zathong.com/wp-content/uploads/2022/10/Dominance-Ice.webp",
    "Armadura Aterrorizante": "https://zathong.com/wp-content/uploads/2022/10/Dreadnaught-Armor.webp",
    "Gema Elegante": "https://zathong.com/wp-content/uploads/2022/10/Elegant-Gem.webp",
    "Talismã Encantado": "https://zathong.com/wp-content/uploads/2022/10/Enchanted-Talisman.webp",
    "Batalha Infinita": "https://zathong.com/wp-content/uploads/2022/10/Endless-Battle.webp",
    "Véu Exótico": "https://zathong.com/wp-content/uploads/2022/10/Exotic-Veil.webp",
    "Pena dos Céus": "https://zathong.com/wp-content/uploads/2022/10/Feather-of-Heaven.webp",
    "Frasco do Oásis": "https://zathong.com/wp-content/uploads/2022/10/Flask-of-the-Oasis.webp",
    "Tempo Fugaz": "https://zathong.com/wp-content/uploads/2022/10/Fleeting-Time.webp",
    "Martelo da Fúria": "https://zathong.com/wp-content/uploads/2022/10/Fury-Hammer.webp",
    "Varinha Genial": "https://zathong.com/wp-content/uploads/2022/10/Genius-Wand.webp",
    "Varinha Brilhante": "https://zathong.com/wp-content/uploads/2022/10/Glowing-Wand.webp",
    "Bastão Dourado": "https://zathong.com/wp-content/uploads/2022/10/Golden-Staff.webp",
    "Lança do Grande Dragão": "https://zathong.com/wp-content/uploads/2022/10/Great-Dragon-Spear.webp",
    "Elmo do Guardião": "https://zathong.com/wp-content/uploads/2022/10/Guardian-Helmet.webp",
    "Garras de Haas": "https://zathong.com/wp-content/uploads/2022/10/Haass-Claws.webp",
    "Cristal Sagrado": "https://zathong.com/wp-content/uploads/2022/10/Holy-Crystal.webp",
    "Machado de Caça": "https://zathong.com/wp-content/uploads/2022/10/Hunter-Strike.webp",
    "Varinha da Rainha de Gelo": "https://zathong.com/wp-content/uploads/2022/10/Ice-Queen-Wand.webp",
    "Imortalidade": "https://zathong.com/wp-content/uploads/2022/10/Immortality.webp",
    "Espada da Legião": "https://zathong.com/wp-content/uploads/2022/10/Legion-Sword.webp",
    "Cetro Relâmpago": "https://zathong.com/wp-content/uploads/2022/10/Lightning-Truncheon.webp",
    "Lâmina Mágica": "https://zathong.com/wp-content/uploads/2022/10/Magic-Blade.webp",
    "Sapatos Mágicos": "https://zathong.com/wp-content/uploads/2022/10/Magic-Shoes.webp",
    "Varinha Mágica": "https://zathong.com/wp-content/uploads/2022/10/Magic-Wand.webp",
    "Arma Maléfica": "https://zathong.com/wp-content/uploads/2022/10/Malefic-Gun.webp",
    "Rugido Maléfico": "https://zathong.com/wp-content/uploads/2022/10/Malefic-Roar.webp",
    "Essência Fundida": "https://zathong.com/wp-content/uploads/2022/10/Molten-Essence.webp",
    "Recipiente Místico": "https://zathong.com/wp-content/uploads/2022/10/Mystic-Container.webp",
    "Machadinha de Ogro": "https://zathong.com/wp-content/uploads/2022/10/Ogre-Tomahawk.webp",
    "Oráculo": "https://zathong.com/wp-content/uploads/2022/10/Oracle.webp",
    "Asas da Rainha": "https://zathong.com/wp-content/uploads/2022/10/Queens-Wings.webp",
    "Armadura Radiante": "https://zathong.com/wp-content/uploads/2022/10/Radiant-Armor.webp",
    "Botas Rápidas": "https://zathong.com/wp-content/uploads/2022/10/Rapid-Boots.webp",
    "Lança Regular": "https://zathong.com/wp-content/uploads/2022/10/Regular-Spear.webp",
    "Meteoro do Desprezo": "https://zathong.com/wp-content/uploads/2022/10/Rogue-Meteor.webp",
    "Meteoro de Ouro Rosa": "https://zathong.com/wp-content/uploads/2022/10/Rose-Gold-Meteor.webp",
    "Alabarda dos Mares": "https://zathong.com/wp-content/uploads/2022/10/Sea-Halberd.webp",
    "Manto do Silêncio": "https://zathong.com/wp-content/uploads/2022/10/Silence-Robe.webp",
    "Perfurador dos Céus": "https://zathong.com/wp-content/uploads/2022/10/Sky-Piercer.webp",
    "Cetro de Starlium": "https://zathong.com/wp-content/uploads/2022/10/Starlium-Scythe.webp",
    "Placas de Aço": "https://zathong.com/wp-content/uploads/2022/10/Steel-Legplates.webp",
    "Botas Ligeiras": "https://zathong.com/wp-content/uploads/2022/10/Swift-Boots.webp",
    "Besta Veloz": "https://zathong.com/wp-content/uploads/2022/10/Swift-Crossbow.webp",
    "Cinto do Trovão": "https://zathong.com/wp-content/uploads/2022/10/Thunder-Belt.webp",
    "Tomo do Mal": "https://zathong.com/wp-content/uploads/2022/10/Tome-of-Evil.webp",
    "Botas Robustas": "https://zathong.com/wp-content/uploads/2022/10/Tough-Boots.webp",
    "Armadura do Crepúsculo": "https://zathong.com/wp-content/uploads/2022/10/Twilight-Armor.webp",
    "Machado de Guerra": "https://zathong.com/wp-content/uploads/2022/10/War-Axe.webp",
    "Botas de Guerreiro": "https://zathong.com/wp-content/uploads/2022/10/Warrior-Boots.webp",
    "Vento da Natureza": "https://zathong.com/wp-content/uploads/2022/10/Wind-of-Nature.webp",
    "Andarilho do Vento": "https://zathong.com/wp-content/uploads/2022/10/Windtalker.webp",
    "Coroa de Inverno": "https://zathong.com/wp-content/uploads/2022/10/Winter-Crown.webp",
    "Lanterna dos Desejos": "https://zathong.com/wp-content/uploads/2022/10/Wishing-Lantern.webp",
    "Quebra-Defesa": "https://zathong.com/wp-content/uploads/2022/10/Malefic-Roar.webp", // Alias for Rugido Maléfico
    "default": "https://zathong.com/wp-content/uploads/2022/10/Antique-Cuirass.webp"
};

export const SPELL_ICONS: Record<string, string> = {
    "Executar": "https://lain.mlbb.ninja/assets/spells/execute.png",
    "Caçar": "https://lain.mlbb.ninja/assets/spells/retribution.png",
    "Inspirar": "https://lain.mlbb.ninja/assets/spells/inspire.png",
    "Petrificar": "https://lain.mlbb.ninja/assets/spells/petrify.png",
    "Purificar": "https://lain.mlbb.ninja/assets/spells/purify.png",
    "Teleporte": "https://lain.mlbb.ninja/assets/spells/arrival.png",
    "Vingança": "https://lain.mlbb.ninja/assets/spells/vengeance.png",
    "Proteção": "https://lain.mlbb.ninja/assets/spells/aegis.png",
    "Avançar": "https://lain.mlbb.ninja/assets/spells/sprint.png",
    "Curar": "https://lain.mlbb.ninja/assets/spells/healing-spell.png",
    "Lampejo": "https://lain.mlbb.ninja/assets/spells/flicker.png",
    "default": "https://lain.mlbb.ninja/assets/spells/flicker.png"
};

export const RATING_STYLES: Record<string, { text: string; border: string }> = {
    "ANULA": { text: "text-green-400", border: "border-green-400" },
    "VANTAGEM": { text: "text-blue-400", border: "border-blue-400" },
    "DESVANTAGEM": { text: "text-red-400", border: "border-red-400" },
    "NEUTRO": { text: "text-gray-400", border: "border-gray-400" },
};

// Base de dados de funções de heróis para permitir a filtragem e sugestões contextuais.
export const HERO_ROLES: Record<string, Role[]> = {
    "Miya": ["Atirador"], "Balmond": ["Soldado"], "Saber": ["Assassino"], "Nana": ["Mago", "Suporte"], "Tigreal": ["Tanque"], "Alucard": ["Soldado", "Assassino"], "Karina": ["Assassino"], "Akai": ["Tanque"], "Franco": ["Tanque"], "Bane": ["Soldado"], "Bruno": ["Atirador"], "Clint": ["Atirador"], "Rafaela": ["Suporte"], "Eudora": ["Mago"], "Zilong": ["Soldado", "Assassino"], "Fanny": ["Assassino"], "Layla": ["Atirador"], "Hayabusa": ["Assassino"], "Gord": ["Mago"], "Kagura": ["Mago"], "Chou": ["Soldado"], "Ruby": ["Soldado", "Tanque"], "Yi Sun-shin": ["Atirador", "Assassino"], "Moskov": ["Atirador"], "Johnson": ["Tanque"], "Cyclops": ["Mago"], "Hilda": ["Soldado", "Tanque"], "Aurora": ["Mago"], "Lapu-Lapu": ["Soldado"], "Vexana": ["Mago"], "Roger": ["Soldado", "Atirador"], "Gatotkaca": ["Tanque"], "Harley": ["Mago", "Assassino"], "Irithel": ["Atirador"], "Grock": ["Tanque"], "Argus": ["Soldado"], "Odette": ["Mago"], "Lancelot": ["Assassino"], "Diggie": ["Suporte"], "Hylos": ["Tanque"], "Zhask": ["Mago"], "Helcurt": ["Assassino"], "Pharsa": ["Mago"], "Lesley": ["Atirador", "Assassino"], "Jawhead": ["Soldado"], "Angela": ["Suporte"], "Gusion": ["Assassino", "Mago"], "Valir": ["Mago"], "Martis": ["Soldado"], "Uranus": ["Tanque"], "Hanabi": ["Atirador"], "Chang'e": ["Mago"], "Kaja": ["Soldado", "Suporte"], "Selena": ["Assassino", "Mago"], "Aldous": ["Soldado"], "Claude": ["Atirador"], "Vale": ["Mago"], "Leomord": ["Soldado"], "Lunox": ["Mago"], "Hanzo": ["Assassino"], "Belerick": ["Tanque"], "Kimmy": ["Atirador", "Mago"], "Thamuz": ["Soldado"], "Harith": ["Mago"], "Minsitthar": ["Soldado"], "Kadita": ["Mago", "Assassino"], "Faramis": ["Suporte", "Mago"], "Granger": ["Atirador"], "Esmeralda": ["Mago", "Tanque"], "Terizla": ["Soldado"], "X.Borg": ["Soldado"], "Ling": ["Assassino"], "Dyrroth": ["Soldado"], "Lylia": ["Mago"], "Baxia": ["Tanque"], "Masha": ["Soldado"], "Wanwan": ["Atirador"], "Silvanna": ["Soldado"], "Cecilion": ["Mago"], "Carmilla": ["Suporte"], "Atlas": ["Tanque"], "Popol and Kupa": ["Atirador"], "Yu Zhong": ["Soldado"], "Luo Yi": ["Mago"], "Benedetta": ["Assassino"], "Khaleed": ["Soldado"], "Barats": ["Tanque", "Soldado"], "Brody": ["Atirador"], "Yve": ["Mago"], "Mathilda": ["Suporte", "Assassino"], "Paquito": ["Soldado", "Assassino"], "Gloo": ["Tanque"], "Beatrix": ["Atirador"], "Natan": ["Atirador", "Mago"], "Aulus": ["Soldado"], "Edith": ["Tanque", "Atirador"], "Floryn": ["Suporte"], "Valentina": ["Mago"], "Melissa": ["Atirador"], "Yin": ["Soldado", "Assassino"], "Xavier": ["Mago"], "Julian": ["Mago", "Soldado"], "Fredrinn": ["Tanque", "Soldado"], "Joy": ["Assassino"], "Novaria": ["Mago"], "Arlott": ["Soldado"], "Ixia": ["Atirador"], "Nolan": ["Assassino"], "Cici": ["Soldado"], "Chip": ["Tanque", "Suporte"]
};