import { Lane, Role, LaneOrNone } from './types';

export const LANE_ICONS: Record<LaneOrNone, string> = {
    'OURO': 'https://i.postimg.cc/rsHmgdzW/icon-lane-1.png',
    'EXP': 'https://i.postimg.cc/Dfp87N5Z/icon-lane-2.png',
    'MEIO': 'https://i.postimg.cc/zvvvnwD8/icon-lane-3.png',
    'ROTAÇÃO': 'https://i.postimg.cc/VL3vCbxP/icon-lane-4.png',
    'SELVA': 'https://i.postimg.cc/fT3kyvgv/icon-lane-5.png',
    'NENHUMA': 'https://i.postimg.cc/0QxwFHxf/sem-lane.png'
};

export const ITEM_ICONS: Record<string, string> = {
    "Couraça Antiga": "https://i.postimg.cc/9F5wRPmG/item-01.png",
    "Botas Arcanas": "https://i.postimg.cc/y8nDbwFP/item-02.png",
    "Cinto de Ares": "https://i.postimg.cc/h477tZBD/item-03.png",
    "Escudo de Atena": "https://i.postimg.cc/2yvq9ywb/item-04.png",
    "Lâmina do Azure": "https://i.postimg.cc/Yq6G140T/item-05.png",
    "Fúria do Berserker": "https://i.postimg.cc/YSqW2ppZ/item-06.png",
    "Escudo de Gelo Negro": "https://i.postimg.cc/26gbxh4N/item-07.png",
    "Armadura de Lâminas": "https://i.postimg.cc/Dzjb8t0Z/item-08.png",
    "Lâmina do Desespero": "https://i.postimg.cc/ydD39v3T/item-09.png",
    "Lâmina dos Sete Mares": "https://i.postimg.cc/Sx4956Hy/item-10.png",
    "Asas Sanguinárias": "https://i.postimg.cc/T3cbXyXn/item-11.png",
    "Peitoral da Força Bruta": "https://i.postimg.cc/MKVRdPPP/item-12.png",
    "Relógio do Destino": "https://i.postimg.cc/G3ZGPwQT/item-13.png",
    "Energia Concentrada": "https://i.postimg.cc/mhfLPS7h/item-14.png",
    "Foice da Corrosão": "https://i.postimg.cc/xjkLbTKS/item-15.png",
    "Elmo Amaldiçoado": "https://i.postimg.cc/LX56w5H4/item-16.png",
    "Espada do Caçador de Demônios": "https://i.postimg.cc/rmHFkTm1/item-17.png",
    "Sapatos de Demônio": "https://i.postimg.cc/T1W22sLZ/item-18.png",
    "Glaive Divino": "https://i.postimg.cc/nL0h3Bfw/item-19.png",
    "Dominância de Gelo": "https://i.postimg.cc/mrbr3VJH/item-20.png",
    "Armadura Aterrorizante": "https://i.postimg.cc/P5bx803H/item-21.png",
    "Gema Elegante": "https://i.postimg.cc/pXFyPmKp/item-22.png",
    "Talismã Encantado": "https://i.postimg.cc/52Wyyfmp/item-23.png",
    "Batalha Infinita": "https://i.postimg.cc/XNhpMfGR/item-24.png",
    "Véu Exótico": "https://i.postimg.cc/Bbd6x3fS/item-25.png",
    "Pena dos Céus": "https://i.postimg.cc/WzDzF3KY/item-26.png",
    "Frasco do Oásis": "https://i.postimg.cc/XJ1XYF2y/item-27.png",
    "Tempo Fugaz": "https://i.postimg.cc/435mjjVP/item-28.png",
    "Martelo da Fúria": "https://i.postimg.cc/QtdHDSq3/item-29.png",
    "Varinha Genial": "https://i.postimg.cc/yNBDQ7gW/item-30.png",
    "Varinha Brilhante": "https://i.postimg.cc/4xpKQY3r/item-31.png",
    "Bastão Dourado": "https://i.postimg.cc/J4fDXNRN/item-32.png",
    "Lança do Grande Dragão": "https://i.postimg.cc/Hsc8jZ1W/item-33.png",
    "Elmo do Guardião": "https://i.postimg.cc/661GWsS1/item-34.png",
    "Garras de Haas": "https://i.postimg.cc/mDm11Krk/item-35.png",
    "Cristal Sagrado": "https://i.postimg.cc/C5dBGJZN/item-36.png",
    "Machado de Caça": "https://i.postimg.cc/90S4JTZj/item-37.png",
    "Varinha da Rainha de Gelo": "https://i.postimg.cc/yNXZsD4F/item-38.png",
    "Imortalidade": "https://i.postimg.cc/NjXXCNdC/item-39.png",
    "Espada da Legião": "https://i.postimg.cc/ZqhdGrgb/item-40.png",
    "Cetro Relâmpago": "https://i.postimg.cc/JnrBnRMS/item-41.png",
    "Lâmina Mágica": "https://i.postimg.cc/Fs733F34/item-42.png",
    "Sapatos Mágicos": "https://i.postimg.cc/MKNRDkmj/item-43.png",
    "Varinha Mágica": "https://i.postimg.cc/cC532Pq2/item-44.png",
    "Arma Maléfica": "https://i.postimg.cc/kG58jqHW/item-45.png",
    "Rugido Maléfico": "https://i.postimg.cc/Y2XQvL4R/item-46.png",
    "Essência Fundida": "https://i.postimg.cc/bJp1tQHC/item-47.png",
    "Recipiente Místico": "https://i.postimg.cc/k4sKFBTn/item-48.png",
    "Machadinha de Ogro": "https://i.postimg.cc/fRS7nWRK/item-49.png",
    "Oráculo": "https://i.postimg.cc/nL84H8st/item-50.png",
    "Asas da Rainha": "https://i.postimg.cc/MGyyHsRf/item-51.png",
    "Armadura Radiante": "https://i.postimg.cc/BZNB2wzx/item-52.png",
    "Botas Rápidas": "https://i.postimg.cc/kXpNpRqG/item-53.png",
    "Lança Regular": "https://i.postimg.cc/nczY2G8N/item-54.png",
    "Meteoro do Desprezo": "https://i.postimg.cc/Ssf7TZxb/item-55.png",
    "Meteoro de Ouro Rosa": "https://i.postimg.cc/rshGcK4h/item-56.png",
    "Alabarda dos Mares": "https://i.postimg.cc/mDsySxRS/item-57.png",
    "Manto do Silêncio": "https://i.postimg.cc/hv48H9Xz/item-58.png",
    "Perfurador dos Céus": "https://i.postimg.cc/FKcxcFtR/item-59.png",
    "Cetro de Starlium": "https://i.postimg.cc/XYrLjcQ9/item-60.png",
    "Placas de Aço": "https://i.postimg.cc/RZ2RN6Dy/item-61.png",
    "Botas Ligeiras": "https://i.postimg.cc/xTTg7Smx/item-62.png",
    "Besta Veloz": "https://i.postimg.cc/gkS4bBqY/item-63.png",
    "Cinto do Trovão": "https://i.postimg.cc/h40ppGXQ/item-64.png",
    "Tomo do Mal": "https://i.postimg.cc/NFbDMd3k/item-65.png",
    "Botas Robustas": "https://i.postimg.cc/FRyDtrGq/item-66.png",
    "Armadura do Crepúsculo": "https://i.postimg.cc/Xqnx4Rzv/item-67.png",
    "Machado de Guerra": "https://i.postimg.cc/FHzWfQsd/item-68.png",
    "Botas de Guerreiro": "https://i.postimg.cc/HL7624MT/item-69.png",
    "Vento da Natureza": "https://i.postimg.cc/0QRcHMGD/item-70.png",
    "Andarilho do Vento": "https://i.postimg.cc/SND1NKqb/item-71.png",
    "Coroa de Inverno": "https://i.postimg.cc/3xqLmbdL/item-72.png",
    "Lanterna dos Desejos": "https://i.postimg.cc/kXnhmb0y/item-73.png",
    "Quebra-Defesa": "https://i.postimg.cc/Y2XQvL4R/item-46.png",
    "default": "https://i.postimg.cc/9F5wRPmG/item-01.png"
};

export const SPELL_ICONS: Record<string, string> = {
    "Executar": "https://i.postimg.cc/xqrJGssM/icon-feitico-batalh-02.png",
    "Caçar": "https://i.postimg.cc/gk63whM3/icon-feitico-batalh-03.png",
    "Caçar de Fogo": "https://i.postimg.cc/RZ7fdBxF/icon-feitico-batalh-04.png",
    "Caçar de Gelo": "https://i.postimg.cc/L8KLjs7w/icon-feitico-batalh-05.png",
    "Caçar Sangrento": "https://i.postimg.cc/8CTvn0Tb/icon-feitico-batalh-06.png",
    "Inspirar": "https://i.postimg.cc/4dd9XH77/icon-feitico-batalh-07.png",
    "Avançar": "https://i.postimg.cc/jjvfV45Y/icon-feitico-batalh-08.png",
    "Revitalizar": "https://i.postimg.cc/3RcDNrmL/icon-feitico-batalh-09.png",
    "Proteção": "https://i.postimg.cc/SxCLP9Cm/icon-feitico-batalh-10.png",
    "Petrificar": "https://i.postimg.cc/6QhrWNMS/icon-feitico-batalh-11.png",
    "Purificar": "https://i.postimg.cc/9f2PHfYZ/icon-feitico-batalh-12.png",
    "Tiro de Chamas": "https://i.postimg.cc/90DZYwc5/icon-feitico-batalh-13.png",
    "Lampejo": "https://i.postimg.cc/1tCDFrhr/icon-feitico-batalh-14.png",
    "Teleporte": "https://i.postimg.cc/L5GfC4sq/icon-feitico-batalh-15.png",
    "Vingança": "https://i.postimg.cc/pVSDXCB2/icon-feitico-batalh-16.png",
    "Curar": "https://i.postimg.cc/nzcvMw5L/icon-feitico-batalh-17.png",
    "default": "https://i.postimg.cc/1tCDFrhr/icon-feitico-batalh-14.png"
};

export const RATING_STYLES: Record<string, { text: string; border: string }> = {
    "PERFEITO": { text: "text-amber-300", border: "border-amber-300" },
    "ANULA": { text: "text-green-400", border: "border-green-400" },
    "VANTAGEM": { text: "text-indigo-400", border: "border-indigo-400" },
    "DESVANTAGEM": { text: "text-red-400", border: "border-red-400" },
    "NEUTRO": { text: "text-gray-400", border: "border-gray-400" },
};

export const ROLE_TAGS: Record<Role, string[]> = {
    'Assassino': ['Burst', 'Mobilidade', 'Finalização'],
    'Mago': ['Dano Mágico', 'Controle', 'Dano em Área'],
    'Atirador': ['Dano Contínuo', 'DPS Físico', 'Longo Alcance'],
    'Soldado': ['Dano/Sustain', 'Lutador', 'Versátil'],
    'Tanque': ['Durabilidade', 'Iniciação', 'CC Pesado'],
    'Suporte': ['Utilidade', 'Cura/Escudo', 'Proteção']
};

// Base de dados de funções de heróis para permitir a filtragem e sugestões contextuais.
export const HERO_ROLES: Record<string, Role[]> = {
    "Miya": ["Atirador"], "Balmond": ["Soldado"], "Saber": ["Assassino"], "Nana": ["Mago", "Suporte"], "Tigreal": ["Tanque"], "Alpha": ["Soldado"], "Alucard": ["Soldado", "Assassino"], "Karina": ["Assassino"], "Akai": ["Tanque"], "Franco": ["Tanque"], "Bane": ["Soldado"], "Bruno": ["Atirador"], "Clint": ["Atirador"], "Rafaela": ["Suporte"], "Eudora": ["Mago"], "Zilong": ["Soldado", "Assassino"], "Fanny": ["Assassino"], "Layla": ["Atirador"], "Hayabusa": ["Assassino"], "Gord": ["Mago"], "Kagura": ["Mago"], "Chou": ["Soldado"], "Ruby": ["Soldado", "Tanque"], "Yi Sun-shin": ["Atirador", "Assassino"], "Moskov": ["Atirador"], "Johnson": ["Tanque"], "Cyclops": ["Mago"], "Hilda": ["Soldado", "Tanque"], "Aurora": ["Mago"], "Lapu-Lapu": ["Soldado"], "Vexana": ["Mago"], "Roger": ["Soldado", "Atirador"], "Gatotkaca": ["Tanque"], "Harley": ["Mago", "Assassino"], "Irithel": ["Atirador"], "Grock": ["Tanque"], "Argus": ["Soldado"], "Odette": ["Mago"], "Lancelot": ["Assassino"], "Diggie": ["Suporte"], "Hylos": ["Tanque"], "Zhask": ["Mago"], "Helcurt": ["Assassino"], "Pharsa": ["Mago"], "Lesley": ["Atirador", "Assassino"], "Jawhead": ["Soldado"], "Angela": ["Suporte"], "Gusion": ["Assassino", "Mago"], "Valir": ["Mago"], "Martis": ["Soldado"], "Uranus": ["Tanque"], "Hanabi": ["Atirador"], "Chang'e": ["Mago"], "Kaja": ["Soldado", "Suporte"], "Selena": ["Assassino", "Mago"], "Aldous": ["Soldado"], "Claude": ["Atirador"], "Vale": ["Mago"], "Leomord": ["Soldado"], "Lunox": ["Mago"], "Hanzo": ["Assassino"], "Belerick": ["Tanque"], "Kimmy": ["Atirador", "Mago"], "Thamuz": ["Soldado"], "Harith": ["Mago"], "Minsitthar": ["Soldado"], "Kadita": ["Mago", "Assassino"], "Faramis": ["Suporte", "Mago"], "Granger": ["Atirador"], "Esmeralda": ["Mago", "Tanque"], "Terizla": ["Soldado"], "X.Borg": ["Soldado"], "Ling": ["Assassino"], "Dyrroth": ["Soldado"], "Lylia": ["Mago"], "Baxia": ["Tanque"], "Masha": ["Soldado"], "Wanwan": ["Atirador"], "Silvanna": ["Soldado"], "Cecilion": ["Mago"], "Carmilla": ["Suporte"], "Atlas": ["Tanque"], "Popol and Kupa": ["Atirador"], "Yu Zhong": ["Soldado"], "Luo Yi": ["Mago"], "Benedetta": ["Assassino"], "Khaleed": ["Soldado"], "Barats": ["Tanque", "Soldado"], "Brody": ["Atirador"], "Yve": ["Mago"], "Mathilda": ["Suporte", "Assassino"], "Paquito": ["Soldado", "Assassino"], "Gloo": ["Tanque"], "Beatrix": ["Atirador"], "Natan": ["Atirador", "Mago"], "Aulus": ["Soldado"], "Edith": ["Tanque", "Atirador"], "Floryn": ["Suporte"], "Valentina": ["Mago"], "Melissa": ["Atirador"], "Yin": ["Soldado", "Assassino"], "Xavier": ["Mago"], "Julian": ["Mago", "Soldado"], "Fredrinn": ["Tanque", "Soldado"], "Joy": ["Assassino"], "Novaria": ["Mago"], "Arlott": ["Soldado"], "Ixia": ["Atirador"], "Nolan": ["Assassino"], "Cici": ["Soldado"], "Chip": ["Tanque", "Suporte"], "Zhuxin": ["Mago"]
};